# config.yaml

# Note that the paths specified below are all data that cant be included in the github repo (primarily due to the size limit of github repo)

# Below we specify the conda env yml file in relative path
conda_env_yaml: "acmg_conda.yml"
conda_env_name: "acmg"

# Below we specify the input vcf file in absolute paths
input_vcf: "/home/yangyxt/git_repos/acmg_auto/data/test_example/TEST_FAM.filtered.vcf.gz"
ped_file: "/home/yangyxt/git_repos/acmg_auto/data/test_example/TEST_FAM.ped"
fam_name: "TEST_FAM"

# Note that the assembly version must be consistent with the reference genome
assembly: hg19

# Below we specify the reference genome in absolute paths because the size of the file is too large to be included in the github repo
ref_genome: "/home/yangyxt/Caches/genomes/hg19/ucsc.hg19.fasta"

# Below we specify the output directory in absolute paths
output_dir: "/home/yangyxt/git_repos/acmg_auto/results"

# Below we specify the number of threads to be used
threads: 5

# Below we specify the allele frequency cutoff for common variants
af_cutoff: 0.01

# Below we specify the path to the gnomAD vcf file for chromosome 1 and we'll use that template to deduce the paths to other chromosome VCF files, the paths should be relatively constant
gnomad_vcf_chrX: "/home/yangyxt/Caches/gnomAD/v4/gnomad.joint.v4.1.sites.hg19.chrX.vcf.gz"

# Below we specify the path to the clinvar vcf file, the path should be relatively constant
clinvar_vcf: "/home/yangyxt/Caches/ClinVar/clinvar.hg19.vcf.gz"


# Below we specify the cache directory for VEP
vep_cache_dir: "/home/yangyxt/Caches/ensembl-vep"
# Below we specify the directory containing the VEP plugins executable files
vep_plugins_dir: "/home/yangyxt/Tools/VEP_plugins"
# Below we specify the directory for storing the VEP plugin caches
vep_plugins_cachedir: "/home/yangyxt/Caches/VEP_plugin_caches"
# The UTRAnnotator plugin cachefile
utr_annotator_file: "/home/yangyxt/Caches/VEP_plugin_caches/UTRannotator/uORF_5UTR_GRCh37_PUBLIC.txt"
# The LOEUF plugin cache file
loeuf_prescore: "/home/yangyxt/Caches/VEP_plugin_caches/LOEUF/loeuf_dataset.tsv.gz"
# The AlphaMissense plugin cache file
alphamissense_prescore: "/home/yangyxt/Caches/VEP_plugin_caches/AlphaMissense/AlphaMissense_hg19.tsv.gz"
# The SpliceAI plugin cache file, snv and indel
spliceai_snv_prescore: "/home/yangyxt/Caches/VEP_plugin_caches/SpliceAI/hg19/spliceai_scores.raw.snv.hg19.vcf.gz"
spliceai_indel_prescore: "/home/yangyxt/Caches/VEP_plugin_caches/SpliceAI/hg19/spliceai_scores.raw.indel.hg19.vcf.gz"
# The PrimateAI plugin cache file
primateai_prescore: "/home/yangyxt/Caches/VEP_plugin_caches/PrimateAI/hg19/PrimateAI_scores_v0.2_GRCh37_sorted.tsv.bgz"
# The Conversation cache file
conversation_file: "/home/yangyxt/Caches/VEP_plugin_caches/Conservations/gerp_conservation_scores.homo_sapiens.GRCh37.bw"


# Below we specify the path to the CADD base directory
cadd_base_dir: "/home/yangyxt/miniconda3/envs/acmg/share/cadd-scripts-1.7.1-0"
cadd_zip_download_url: "https://github.com/kircherlab/CADD-scripts/archive/refs/tags/v1.7.zip"
cadd_GRCh37_anno_md5: "22549309c65de8d25e903695aa4f749f"
cadd_GRCh38_anno_md5: "205d3e702df3565efb424e2ca80c9d25"
cadd_GRCh37_snv_anno_url: "https://krishna.gs.washington.edu/download/CADD/v1.7/GRCh37/whole_genome_SNVs_inclAnno.tsv.gz"
cadd_GRCh37_snv_anno_md5: "1b89cfd7da4e2a8f336c1ec33a6f44eb"
cadd_GRCh37_indel_anno_url: "https://krishna.gs.washington.edu/download/CADD/v1.7/GRCh37/gnomad.genomes-exomes.r4.0.indel_inclAnno.tsv.gz"
cadd_GRCh37_indel_anno_md5: "3d88f8fde9df07060b4f8fe07a0d5d5d"
cadd_GRCh38_snv_anno_url: "https://krishna.gs.washington.edu/download/CADD/v1.7/GRCh38/whole_genome_SNVs_inclAnno.tsv.gz"
cadd_GRCh38_snv_anno_md5: "ed9d3e029686375e2ac80e96b5d0067a"
cadd_GRCh38_indel_anno_url: "https://krishna.gs.washington.edu/download/CADD/v1.7/GRCh38/gnomad.genomes.r4.0.indel_inclAnno.tsv.gz"
cadd_GRCh38_indel_anno_md5: "00ce2d2431a6ec3324b23ff625f4e0cd"
cadd_version: "v1.7"
