# config.yaml

# Note that the paths specified below are all data that cant be included in the github repo (primarily due to the size limit of github repo)

# Below we specify the conda env yml file in relative path
conda_env_yaml: "acmg_conda.yml"

# Below we specify the input vcf file in absolute paths
input_vcf: "/home/yangyxt/git_repos/acmg_auto/data/test_example/TEST_FAM.vcf.gz"
ped_file: "/home/yangyxt/git_repos/acmg_auto/data/test_example/TEST_FAM.ped"
fam_name: "Family1"

# Note that the assembly version must be consistent with the reference genome
assembly: "hg19"

# Below we specify the reference genome in absolute paths because the size of the file is too large to be included in the github repo
ref_genome: "/home/yangyxt/Caches/genomes/hg19/ucsc.hg19.fasta"

# Below we specify the output directory in absolute paths
output_dir: "/home/yangyxt/git_repos/acmg_auto/results"

# Below we specify the number of threads to be used
threads: 8
af_cutoff: 0.05
gnomad_vcf_dir: "/home/yangyxt/git_repos/acmg_auto/data/gnomad"
clinvar_vcf: "/home/yangyxt/git_repos/acmg_auto/data/clinvar/clinvar.vcf.gz"
vep_cache_dir: "/home/yangyxt/Caches/ensembl-vep"
vep_plugins_dir: "/home/yangyxt/Tools/VEP_plugins"
vep_plugins_cachedir: "/home/yangyxt/Caches/VEP_plugin_caches"
script_dir: "/home/yangyxt/git_repos/acmg_auto/scripts"
