tmp_dir: example/smoke_runs/hg38/tmp
assembly: hg38
ref_genome: /paedyl01/disk1/yangyxt/indexed_genome/hg38/ucsc.hg38.fasta
conda_env_yaml: acmg_conda_rough.yml
conda_env_name: priva_acmg
hg38_hg19_chain: hg38ToHg19.over.chain.gz
gnomad_vcf_dir: example/smoke_data/hg38/resources
clinvar_vcf_dir: example/smoke_data/hg38/resources
vep_cache_dir: /paedyl01/disk1/yangyxt/public_data/VEP_caches
vep_plugins_dir: /paedyl01/disk1/yangyxt/public_data/VEP_plugins
vep_plugins_cachedir: /paedyl01/disk1/yangyxt/public_data/VEP_plugins_caches
cadd_parent_dir: /paedyl01/disk1/yangyxt/Tools/CADD
input_vcf: example/smoke_data/hg38/input/clinvar.hg38.demo20.seed20250429.noCSQ.anno.vcf.gz
ped_file: ''
output_dir: example/smoke_runs/hg38/output
hub_file_dir: example/smoke_data
hub_vcf_file: example/smoke_data/hg38/resources/hg38.demo20.hub.anno.vcf.gz
hub_cadd_file: example/smoke_data/hg38/resources/hg38.demo20.hub.cadd.tsv
extreme_rare_PAF: 0.0001
exp_disease_incidence: 0.001
threads: 2
threads_per_fam: 1
af_cutoff: 0.05
alt_disease_vcf: ''
control_vcf: example/smoke_data/hg38/input/clinvar.hg38.demo20.seed20250429.noCSQ.anno.vcf.gz
pp1_vcf: ''
pp1_ped: ''
gnomad_vcf_chrX: example/smoke_data/hg38/resources/gnomad.demo.sites.hg38.chrX.vcf.gz
clinvar_vcf: example/smoke_data/hg38/resources/clinvar.hg38.demo20.vcf.gz
clinvar_aa_stat: example/smoke_data/hg38/resources/clinvar.hg38.demo20.vep.aa_change.stats.pkl
clinvar_splice_stat: example/smoke_data/hg38/resources/clinvar.hg38.demo20.vep.splice_change.stats.pkl
clinvar_patho_af_stat: example/smoke_data/hg38/resources/clinvar.hg38.demo20.vep.patho_af_stat.pkl
clinvar_patho_exon_af_stat: example/smoke_data/hg38/resources/clinvar.hg38.demo20.vep.patho_exon_af_stat.pkl
clinvar_gene_stat: clinvar_2star_stats.pkl.gz
utr_annotator_file: /paedyl01/disk1/yangyxt/public_data/VEP_plugins_caches/UTRannotator/uORF_5UTR_GRCh38_PUBLIC.txt
loeuf_prescore: loeuf_dataset.tsv.gz
loftee_parent_dir: /paedyl01/disk1/yangyxt/public_data/VEP_plugins/LoFtee_repos
loftee_repo: /paedyl01/disk1/yangyxt/public_data/VEP_plugins/LoFtee_repos/loftee-hg38
human_ancestor_fasta: /paedyl01/disk1/yangyxt/public_data/VEP_plugins_caches/LoFtee/hg38/human_ancestor.fa.gz
loftee_conservation_file: /paedyl01/disk1/yangyxt/public_data/VEP_plugins_caches/LoFtee/hg38/loftee.sql
gerp_bigwig: /paedyl01/disk1/yangyxt/public_data/VEP_plugins_caches/LoFtee/hg38/gerp_conservation_scores.homo_sapiens.bw
alphamissense_prescore: /paedyl01/disk1/yangyxt/public_data/VEP_plugins_caches/AlphaMissense/AlphaMissense_hg38.tsv.gz
alphamissense_vcf: /paedyl01/disk1/yangyxt/public_data/VEP_plugins_caches/AlphaMissense/AlphaMissense_hg38.vcf.gz
alphamissense_vep_vcf: /paedyl01/disk1/yangyxt/public_data/VEP_plugins_caches/AlphaMissense/AlphaMissense_hg38.vep.vcf.gz
alphamissense_pd_stat: /paedyl01/disk1/yangyxt/public_data/VEP_plugins_caches/AlphaMissense/AlphaMissense_hg38.vep.prot.domain.stats.pkl
alphamissense_tranx_domain_map: example/smoke_data/hg38/resources/transcript_pp_domain_mapping.hg38.demo20.pkl
alphamissense_intolerant_domains: example/smoke_data/hg38/resources/domain_tolerance_analysis.hg38.demo20.tsv
alphamissense_intolerant_motifs: /paedyl01/disk1/yangyxt/public_data/VEP_plugins_caches/AlphaMissense/AlphaMissense_hg38.kde.pkl
all_intolerant_domains: example/smoke_data/hg38/resources/all_intolerant_domains.hg38.demo20.pkl
pm1_regions_pkl: example/smoke_data/hg38/resources/pm1_regions.hg38.demo20.pkl
conservation_file: /paedyl01/disk1/yangyxt/public_data/VEP_plugins_caches/Conservation/gerp_conservation_scores.homo_sapiens.GRCh38.bw
splicevault_url: https://ftp.ensembl.org/pub/current_variation/SpliceVault/SpliceVault_data_GRCh38.tsv.gz
splicevault_prescore: /paedyl01/disk1/yangyxt/public_data/VEP_plugins_caches/SpliceVault/SpliceVault_data_GRCh38.tsv.gz
cadd_base_dir: /paedyl01/disk1/yangyxt/Tools/CADD/CADD-scripts-1.7.2
primateai_prescore: /paedyl01/disk1/yangyxt/public_data/VEP_plugins_caches/PrimateAI/hg38/PrimateAI_scores_v0.2_GRCh38_sorted.tsv.bgz
spliceai_snv_prescore: /paedyl01/disk1/yangyxt/public_data/VEP_plugins_caches/SpliceAI/hg38/spliceai_scores.raw.snv.hg38.vcf.gz
spliceai_indel_prescore: /paedyl01/disk1/yangyxt/public_data/VEP_plugins_caches/SpliceAI/hg38/spliceai_scores.raw.indel.hg38.vcf.gz
repeat_region_file_name: ucsc.hg38.fasta.repeat.bed.gz
cadd_zip_download_url: https://github.com/kircherlab/CADD-scripts/archive/refs/tags/v1.7.2.zip
cadd_GRCh37_anno_md5: 22549309c65de8d25e903695aa4f749f
cadd_GRCh38_anno_md5: 205d3e702df3565efb424e2ca80c9d25
cadd_GRCh37_snv_anno_url: https://krishna.gs.washington.edu/download/CADD/v1.7/GRCh37/whole_genome_SNVs_inclAnno.tsv.gz
cadd_GRCh37_snv_anno_md5: 1b89cfd7da4e2a8f336c1ec33a6f44eb
cadd_GRCh37_indel_anno_url: https://krishna.gs.washington.edu/download/CADD/v1.7/GRCh37/gnomad.genomes-exomes.r4.0.indel_inclAnno.tsv.gz
cadd_GRCh37_indel_anno_md5: 3d88f8fde9df07060b4f8fe07a0d5d5d
cadd_GRCh38_snv_anno_url: https://krishna.gs.washington.edu/download/CADD/v1.7/GRCh38/whole_genome_SNVs_inclAnno.tsv.gz
cadd_GRCh38_snv_anno_md5: ed9d3e029686375e2ac80e96b5d0067a
cadd_GRCh38_indel_anno_url: https://krishna.gs.washington.edu/download/CADD/v1.7/GRCh38/gnomad.genomes.r4.0.indel_inclAnno.tsv.gz
cadd_GRCh38_indel_anno_md5: 00ce2d2431a6ec3324b23ff625f4e0cd
cadd_version: v1.7
interpro_xml_gz_url: https://ftp.ebi.ac.uk/pub/databases/interpro/current_release/interpro.xml.gz
interpro_mapping_pickle: example/smoke_data/hg38/resources/Interpro_entry_mapping.hg38.demo20.pkl.gz
clingen_map: example/smoke_data/hg38/resources/clingen_map.hg38.demo20.pkl.gz
gene_dosage_sensitivity: example/smoke_data/hg38/resources/gene_dosage_sensitivity.hg38.demo20.tsv
cds_fasta_file: /paedyl01/disk1/yangyxt/public_data/VEP_plugins_caches/Ensembl_CDS/Homo_sapiens.GRCh38.cds.all.fa.gz
mavedb_url: https://ftp.ensembl.org/pub/current_variation/MaveDB/MaveDB_variants.tsv.gz
mavedb_file: /paedyl01/disk1/yangyxt/public_data/VEP_plugins_caches/MaveDB/MaveDB_variants.hg38.tsv.gz
pext_enabled: false
pext_tissues: ''
pext_mean_bw: ''
pext_tissue_bw_dir: ''
